#### general settings
name: train_RDVR-H265-Stage2-Step1
use_tb_logger: true
model: MIMO-VRN
distortion: sr
scale: 2
gpu_ids: [0]
gop: 5

#### datasets
datasets:
  train:
    name: Vimeo90K
    mode: Vimeo90K
    interval_list: [0]
    random_reverse: false
    border_mode: false
    dataroot_GT: /hy-tmp/Datasets/MIMO-VRN-main/Datasets/vimeo90k/vimeo90k_train_GT7.lmdb
    dataroot_LQ: /hy-tmp/Datasets/MIMO-VRN-main/Datasets/vimeo90k/vimeo90k_train_GT7.lmdb #LQ path is not used
    cache_keys: Vimeo90K_train_keys.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 6
    batch_size: 16
    GT_size: 144
    LQ_size: 36
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: Vid4
    mode: video_test

    dataroot_GT: /hy-tmp/Datasets/Small_REDS4/GT
    dataroot_LQ: /hy-tmp/Datasets/Small_REDS4/GT #LQ path is not used

    N_frames: 1
    padding: 'new_info'
    pred_interval: -1

#### network structures
network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [6]
  scale: 2
  init: xavier
  block_num_rbm: 8
  #h265_all_default: true
  h265_q_test_or_val: 16.5
  
#### path
path:
  pretrain_model_G: ../../RDVR-H265-Stage1/trained_models/RDVR-H265-Stage1.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.5
  niter: 25000
  warmup_iter: -1  # no warm up
  lr_scheme: MultiStepLR
  lr_steps: [19000, 20000, 21000, 22000, 23000, 24000]

  lr_gamma: 0.5
  pixel_criterion_forw: l2
  pixel_criterion_back: l1
  manual_seed: 10

  val_freq: !!float 1000
  lambda_fit_forw: 640
  lambda_rec_back: 1
  lambda_center: 0
  weight_decay_G: !!float 1e-12
  #gradient_clipping: 10
  lambda_modified_y: 0
  
  noise_type: h265
  h265_sug: true
  lambda_mimick_loss: 0
  #loss_multiplier: 1000
  
  fh_loss: l2
  h265_deart: False
  h265_q_train: [11,21]
  lambda_corr: !!float 1e-5
  stp_hidden_c: 24 
  stp_denseblock_innerc: 12

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 25000